<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Taxonomy.Core\Taxonomy.Core.csproj" />
    <ProjectReference Include="..\..\src\Taxonomy.Ingest\Taxonomy.Ingest.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\data\structure_released.xml" Link="TestData\structure_released.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
